export const Books = [
  {
    id: 1,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    coverImage: "https://covers.openlibrary.org/b/id/8225266-L.jpg",
    description: "A novel about the American dream and the roaring 1920s.",
  },
  {
    id: 2,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    coverImage: "https://covers.openlibrary.org/b/id/8224616-L.jpg",
    description: "A story of racial injustice in the Deep South.",
  },
  {
    id: 3,
    title: "1984",
    author: "George Orwell",
    coverImage: "https://covers.openlibrary.org/b/id/8243894-L.jpg",
    description: "A dystopian novel about totalitarianism and surveillance.",
  },
  {
    id: 4,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    coverImage: "https://covers.openlibrary.org/b/id/7944739-L.jpg",
    description: "A classic romance novel set in Regency-era England.",
  },
  {
    id: 5,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    coverImage: "https://covers.openlibrary.org/b/id/8243336-L.jpg",
    description: "A novel about teenage rebellion and alienation.",
  },
  {
    id: 6,
    title: "Moby Dick",
    author: "Herman Melville",
    coverImage: "https://covers.openlibrary.org/b/id/8262670-L.jpg",
    description: "An epic tale of revenge and the sea.",
  },
  {
    id: 7,
    title: "War and Peace",
    author: "Leo Tolstoy",
    coverImage: "https://covers.openlibrary.org/b/id/8243892-L.jpg",
    description:
      "A sweeping narrative of Russian society during the Napoleonic era.",
  },
  {
    id: 8,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    coverImage: "https://covers.openlibrary.org/b/id/8355820-L.jpg",
    description:
      "A fantasy adventure about a hobbit's journey to reclaim a treasure.",
  },
  {
    id: 9,
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    coverImage: "https://covers.openlibrary.org/b/id/8231137-L.jpg",
    description: "A psychological exploration of guilt and redemption.",
  },
  {
    id: 10,
    title: "The Odyssey",
    author: "Homer",
    coverImage: "https://covers.openlibrary.org/b/id/8362789-L.jpg",
    description:
      "An ancient epic about Odysseus' journey home after the Trojan War.",
  },
  {
    id: 11,
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    coverImage: "https://covers.openlibrary.org/b/id/8340606-L.jpg",
    description:
      "A gothic romance novel with themes of independence and morality.",
  },
  {
    id: 12,
    title: "Wuthering Heights",
    author: "Emily Brontë",
    coverImage: "https://covers.openlibrary.org/b/id/8351742-L.jpg",
    description: "A tragic love story set on the Yorkshire moors.",
  },
  {
    id: 13,
    title: "The Divine Comedy",
    author: "Dante Alighieri",
    coverImage: "https://covers.openlibrary.org/b/id/8392727-L.jpg",
    description: "An allegorical journey through Hell, Purgatory, and Heaven.",
  },
  {
    id: 14,
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    coverImage: "https://covers.openlibrary.org/b/id/8389202-L.jpg",
    description:
      "An epic fantasy tale of the battle against evil in Middle-earth.",
  },
  {
    id: 15,
    title: "Brave New World",
    author: "Aldous Huxley",
    coverImage: "https://covers.openlibrary.org/b/id/8317170-L.jpg",
    description:
      "A dystopian novel exploring a technologically advanced society.",
  },
  {
    id: 16,
    title: "The Alchemist",
    author: "Paulo Coelho",
    coverImage: "https://covers.openlibrary.org/b/id/8268043-L.jpg",
    description: "A philosophical tale about following one's dreams.",
  },
  {
    id: 17,
    title: "Frankenstein",
    author: "Mary Shelley",
    coverImage: "https://covers.openlibrary.org/b/id/8208249-L.jpg",
    description: "A Gothic novel about the dangers of scientific ambition.",
  },
  {
    id: 18,
    title: "Dracula",
    author: "Bram Stoker",
    coverImage: "https://covers.openlibrary.org/b/id/8324080-L.jpg",
    description: "A classic vampire tale set in Victorian England.",
  },
  {
    id: 19,
    title: "The Iliad",
    author: "Homer",
    coverImage: "https://covers.openlibrary.org/b/id/8351674-L.jpg",
    description: "An epic poem about the Trojan War.",
  },
  {
    id: 20,
    title: "A Tale of Two Cities",
    author: "Charles Dickens",
    coverImage: "https://covers.openlibrary.org/b/id/8227911-L.jpg",
    description: "A historical novel set during the French Revolution.",
  },
  {
    id: 21,
    title: "Great Expectations",
    author: "Charles Dickens",
    coverImage: "https://covers.openlibrary.org/b/id/8206807-L.jpg",
    description: "A coming-of-age story of an orphan named Pip.",
  },
  {
    id: 22,
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    coverImage: "https://covers.openlibrary.org/b/id/8324121-L.jpg",
    description: "A novel about vanity and moral corruption.",
  },
  {
    id: 23,
    title: "The Scarlet Letter",
    author: "Nathaniel Hawthorne",
    coverImage: "https://covers.openlibrary.org/b/id/8357805-L.jpg",
    description: "A story of sin and redemption in Puritan New England.",
  },
  {
    id: 24,
    title: "Anna Karenina",
    author: "Leo Tolstoy",
    coverImage: "https://covers.openlibrary.org/b/id/8339526-L.jpg",
    description: "A tragic romance set in 19th-century Russia.",
  },
  {
    id: 25,
    title: "The Count of Monte Cristo",
    author: "Alexandre Dumas",
    coverImage: "https://covers.openlibrary.org/b/id/8296794-L.jpg",
    description: "A tale of betrayal, revenge, and redemption.",
  },
  {
    id: 26,
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    coverImage: "https://covers.openlibrary.org/b/id/8360212-L.jpg",
    description: "A comedic tale of chivalry and delusion.",
  },
  {
    id: 27,
    title: "Ulysses",
    author: "James Joyce",
    coverImage: "https://covers.openlibrary.org/b/id/8334975-L.jpg",
    description: "A modernist novel about a day in the life of Leopold Bloom.",
  },
  {
    id: 28,
    title: "The Old Man and the Sea",
    author: "Ernest Hemingway",
    coverImage: "https://covers.openlibrary.org/b/id/8342524-L.jpg",
    description: "A story of resilience and the struggle against nature.",
  },
  {
    id: 29,
    title: "Les Misérables",
    author: "Victor Hugo",
    coverImage: "https://covers.openlibrary.org/b/id/8344824-L.jpg",
    description: "A tale of redemption and revolution in 19th-century France.",
  },
  {
    id: 30,
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    coverImage: "https://covers.openlibrary.org/b/id/8323945-L.jpg",
    description: "A philosophical exploration of faith, doubt, and morality.",
  },
];
